# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy 1'

# on é uma regra de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on: 
  workflow_run:
   workflows: ['Execução Manual']
   types:
    - completed

# trabalhos/tarefas dentro do pipeline são jobs 
jobs:
  e2e-tests: 


    #maquina que o job vai executar = runs-on
    runs-on: ubuntu-latest

    #steps =  passos do script de build
    steps:
      #no steps coloca clone do projeto : actions/checkout@v4
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #instalação das dependencias 
      - name: Instalando dependências
        run: yarn

      #instalação do plawyright
      - name: Instalando Playwright
        run: yarn playwright install
    
      #executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
